version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8089:8080"
      - "50000:50000"  # Pour les agents si besoin
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # pour permettre à Jenkins de lancer d'autres conteneurs
    networks:
      - my-network  

volumes:
  jenkins_home:

networks:
  my-network:
    external: true
    name: my-network