FROM bitnami/spark:3.3

USER root

# Installer pip et la lib requests
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --no-cache-dir requests && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER 1001
