services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    hostname: spark-master         # ✅ AJOUT ICI
    environment:
      - SPARK_MODE=master
    ports:
      - "8085:8080"
      - "7077:7077"
    volumes:
      - /c/Users/USER/Desktop/mspr/vlib/Jobs:/opt/spark-jobs
    networks:
      - my-network

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - "8083:8081"
    depends_on:
      - spark-master
    networks:
      - my-network

networks:
  my-network:
    external: true
    name: my-network
