version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - my-network

  airflow-init:
    image: apache/airflow:2.8.0-python3.8
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 6c5e5d219c4d8d8fc26fd4c2b18cdd93c7858a1d4d1b2c20f3154bc4f3813be5
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-docker
    entrypoint: >
      /bin/bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    networks:
      - my-network

  airflow-webserver:
    image: apache/airflow:2.8.0-python3.8
    container_name: airflow_web
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 6c5e5d219c4d8d8fc26fd4c2b18cdd93c7858a1d4d1b2c20f3154bc4f3813be5
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-docker
    command: >
      bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow webserver"
    volumes:
      - ${LOCAL_JOBS_PATH}:/opt/airflow/Jobs
      - ${LOCAL_JOBS_PATH}:/opt/spark-jobs
      - ${LOCAL_DAGS_PATH}:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - my-network

  airflow-scheduler:
    image: apache/airflow:2.8.0-python3.8
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 6c5e5d219c4d8d8fc26fd4c2b18cdd93c7858a1d4d1b2c20f3154bc4f3813be5
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-docker
    command: scheduler
    volumes:
      - ${LOCAL_JOBS_PATH}:/opt/spark-jobs
      - ${LOCAL_DAGS_PATH}:/opt/airflow/dags
    env_file:
      - .env
    networks:
      - my-network

volumes:
  postgres-db-volume:

networks:
  my-network:
    external: true
    name: my-network
