services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1   # ✅ mis à jour ici
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - my-network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1   # ✅ mis à jour ici
    volumes:
      - datanode1-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - my-network

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1   # ✅ mis à jour ici
    volumes:
      - datanode2-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - my-network

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:

networks:
  my-network:
    external: true
    name: my-network
